colleges_students_backbone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home', to: 'colleges#home'
  get '/api/students/view', to: 'students#view'
  get '/api/colleges/view', to: 'colleges#view'
  post '/home/search', to: 'colleges#search'
  post '/home/filter', to: 'students#filter'
  get '/home/query', to: 'students#query'
  
  resources :students
  resources :colleges
end

colleges_students_backbone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

colleges_students_backbone/app/models/college.rb
class College < ApplicationRecord
    validates :establish, presence: true, numericality: { only_integer: true}
    validates :name, presence: true, format: {with: /\A[a-zA-Z]+\z/ }
    has_many :students, dependent: :destroy
end

colleges_students_backbone/app/models/student.rb
class Student < ApplicationRecord
    belongs_to :college
    validates :maths, :physics, :chemistry, :college_id, :regid, :year, presence: true, numericality: { only_integer: true}
    validates :dept, presence: true

    ## this method computes the change in marks for two provided year and
    ## also computes the total of rows of each group
    def self.compute_change_and_total!(marks_change, total_marks, student, year1, year2, total)
        student.keys.each do |key|
            change_row = {"maths"=> 0, "physics" => 0, "chemistry" => 0}
            total_row = {"maths"=> 0, "physics" => 0, "chemistry" => 0}
            math1, math2, phy1, phy2, chem1, chem2 = [0,0,0,0,0,0]
            student[key].each do |stu|
                total_row["maths"] += stu['maths']
                total_row["physics"] += stu['physics']
                total_row["chemistry"] += stu['chemistry']
                if !year1.nil? && !year2.nil?
                    if stu['year'] == year1
                        math1 = stu['maths']
                        phy1 = stu['physics']
                        chem1 = stu['chemistry']
                    elsif stu['year'] == year2
                        math2 = stu['maths']
                        phy2 = stu['physics']
                        chem2 = stu['chemistry']
                    end
                end
            end
            if !year1.nil? && !year2.nil?
                change_row["maths"] = math1 - math2
                change_row["physics"] = phy1 - phy2
                change_row["chemistry"] = chem1 - chem2
                marks_change[key] = change_row
            end
            if total == "true"
                total_marks[key] = total_row
            end
        end
        return total_marks, marks_change
    end
end

colleges_students_backbone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

colleges_students_backbone/app/controllers/colleges_controller.rb
class CollegesController < ApplicationController

	def home; 
	end

	def view
	    @colleges = College.all
	    render :json => @colleges
	end

	def search
		str = params[:college][:name]
		@college = College.where('name like ?', "%#{str}%")
	end

	def index
		@college = College.all
	end

	def show
		@student = Student.select('regid, dept, year').where(college_id: params[:id])
	end

	def new
		@college = College.new
	end

	def create
		@college = College.new(params.require(:college).permit!)
		@college.save
		redirect_to colleges_path
	end

	def edit
		@college = College.find(params[:id])
	end

	def update
		@college = College.find(params[:id])
		@college.update_attributes(params.require(:college).permit!)
		redirect_to colleges_path
	end

	def destroy
		college = College.find(params[:id])
		college.destroy
		redirect_to colleges_path
	end

end

colleges_students_backbone/app/controllers/students_controller.rb
class StudentsController < ApplicationController

	def view
		
	    @students = Student.all
	    render :json => @students
	end

	def filter
		@students = Student.order(params[:sort])
		@students = @students.all.group_by(&:"#{params[:group]}")
		@display = params[:display]

		first = 0
		second = 0
		@marks_change = {}
		@total_marks = {}

		year1 = !params[:year1].empty? ? Integer(params[:year1]) : nil
		year2 = !params[:year2].empty? ? Integer(params[:year2]) : nil
		total = params[:total]

		@total_marks, @marks_change = Student.compute_change_and_total!(@marks_change, @total_marks, @students, year1, year2, total)

		render json: [@students, @marks_change, @total_marks, @display]
	end

	def query; end

	def index
		@students = Student.all
		colleges = []
		@students.each { |student| colleges.push(student.college.name) }
		@details = @students.zip(colleges)
		return @details
	end

	def new
		@student = Student.new
	end

	def create
		student = Student.new(params.require(:student).permit!)
		student.save	
		col_name = College.select('name').find(params[:student][:college_id])
		col_name = col_name.name[0...2]
		student.update_attribute :extended_sid, "#{student.id}_#{col_name}"
		redirect_to students_path
	end

	def edit
		@student = Student.find(params[:id])
	end

	def update
		student = Student.find(params[:id])
		student.update_attributes(params.require(:student).permit!)
		redirect_to students_path
	end

	def destroy
		student = Student.find(params[:id])
		student.destroy
		redirect_to students_path
	end
end

colleges_students_backbone/app/helpers/application_helper.rb
module ApplicationHelper
end

colleges_students_backbone/app/helpers/colleges_helper.rb
module CollegesHelper
end

colleges_students_backbone/app/helpers/students_helper.rb
module StudentsHelper
end

colleges_students_backbone/app/views/colleges/edit.html.erb
<style>
  .block{
     background-color: orange;
     box-shadow: 0px 0px 20px;
     width:700px;
     height: 550px;
     text-align: center;
     margin-left:22%;
  }
 .links{
     color:#f1f1f1;
     font-size:40px;
     font-weight:bold;
     text-decoration: none;
  }
 .filling{
     padding:3px;
     width:250px;
     height:25px;
     font-size:25px;
  }
 .press{
     padding:3px;
     width:250px;
     font-size:25px;
     color:#0099ff;
  }
</style>
<h1 align="center" style="color: #0099ff;"><%= t("edit_College") %></h1>
<body bgcolor="#f1f1f1" >
  <div class="block">
      <%= form_for :college, url: college_path(@college), method: "put" do |f|  %>
           <br><br>
           <p>
              <%= f.text_field :name, placeholder: "College Name", class: "filling", :required => true %><br><br>
              <%= f.number_field :establish, placeholder: "Established Year", class: "filling", :required => true%><br><br>
              <%= f.submit "Submit", class: "press"%>
           </p>
      <% end %>
      <p><%= link_to "Home", "/home", {:class=>"links"} %></p>
  </div>
</body>

colleges_students_backbone/app/views/colleges/home.html.erb
<html>
  <head>
    <style>
       .left_div{
          float: left;
          background-color: orange;
          width:400px;
          height: 300px;
          margin-left: 2%;
          box-shadow: 0px 0px 10px black;
          text-align:center;
        }
       .mid_div{
          float: left;
          background-color: #0099ff;
          width:400px;
          height: 300px;
          margin-left: 1%;
          box-shadow: 0px 0px 20px black;
          text-align:center;
        }
       .right_div{
          float: right;
          background-color: orange;
          width:400px;
          height: 300px;
          margin-right:2%;
          box-shadow: 0px 0px 20px black;
          text-align:center;
        }
       .links{
          color:#f1f1f1;
          font-size:40px;
          font-weight:bold;
          text-decoration: none;
        }
       .filling{
          padding:3px;
          width:250px;
          height:20px;
          font-size:20px;
        }
       .press{
          padding:3px;
          width:100px;
          font-size:18px;
          color:#0099ff;
        }
        #container{
          width: 1200px;
          text-align:center;
          box-shadow: 0px 0px 20px black;
          display:inline-block;
          margin-top:20px;
          background-color:orange;
        }
        #option{
          width: 1200px;
          text-align:center;
          box-shadow: 0px 0px 20px black;
          display:inline-block;
          margin-top:20px;
          background-color:#0099ff;
        }
    </style>
    <h1 align="center" style="color: #0099ff; font-size:40px;"><%= t("app_title") %></h1>
  </head>
  <body bgcolor="#f1f1f1">
    
      <p>
        <div class="left_div"><br><br><br><br>
          <%= link_to "Add College", new_college_path, {:class=>"links"}%><br><br>
          <%= link_to "View all Colleges", colleges_path, {:class=>"links"}%>
        </div>
        <div class="mid_div" ><br><br><br>
          <%= form_for :college, url: home_search_path do |f| %>
            <%= f.text_field :name, placeholder: "College Search", class:"filling", :required => true %> <br><br>
            <%= f.submit "Search", class: "press" %>
          <% end %>
          <br><br><br>
          <%= link_to "Query On Student", "/home/query/", {:class=>"links"} %><br><br>
        </div>
        <div class="right_div" id="inside"><br><br><br><br>
          <%= link_to "Add Student", new_student_path, {:class=>"links"} %><br><br>
          <%= link_to "View all Student", students_path, {:class=>"links"}%>
        </div>
      </p>
      <center>
      <div id="option" align="center"></div>
      <div id="container" align="center"></div>
      </center>
   
  </body>
</html>

colleges_students_backbone/app/views/colleges/index.html.erb
<html>
  <head>
    <style>
        .block{
           background-color: orange;
           box-shadow: 0px 0px 20px;
           width:750px;
           height: 550px;
           text-align: center;
           margin-left:22%;
        }
        .links{
           color:#f1f1f1;
           font-size:40px;
           font-weight:bold;
           text-decoration: none;
        }
        table {
           border-collapse: collapse;
           text-align: center;
           margin-left:5%;
        }
        table, td, th {
            border: 2px solid #0099ff;
            padding: 4px;
        }
        .jump{
            color:#f1f1f1;
            font-weight:bold;
            text-decoration: none;
        }
        .jump:hover
        {
            font-size:120%;
        }
    </style>
    <h1 align="center" style="color: #0099ff;"><%= t("available_colleges") %></h1>
  </head>
  <body bgcolor="#f1f1f1">
    <div class="block">
      <% if !@college.empty? %><br><br>
        <table border="1">
          <tr>
            <th>College Name</th>
            <th>Established Year</th>
            <th>Edit Link</th>
            <th>Delete Link</th>
            <th>Students Link</th>
          </tr>
          <% @college.each do |item| %>
            <tr>
              <td><%= item.name %></td>
              <td><%= item.establish %></td>
              <td><%= link_to 'Edit College', edit_college_path(item.id), {:class=>"jump"} %></td>
              <td><%= link_to 'Delete College', college_path(item.id), method: "delete", class: "jump"%></td>
              <td><%= link_to 'College Students', college_path(item.id), {:class=>"jump"} %></td>
            </tr>
          <% end %>
        </table>
      <% else %>
          <br><br><p>No College available</p>
      <% end %>
      <p>
        <a href="home/#" onclick="router.navigate('/home/#', true);" class='links'>Home</a>
      </p>
    </div>
  </body>
</html>

colleges_students_backbone/app/views/colleges/new.html.erb
<style>
  .block{
     background-color: orange;
     box-shadow: 0px 0px 20px;
     width:700px;
     height: 550px;
     text-align: center;
     margin-left:22%;
  }
  .links{
     color:#f1f1f1;
     font-size:40px;
     font-weight:bold;
     text-decoration: none;
  }
  .filling{
     padding:3px;
     width:250px;
     height:25px;
     font-size:25px;
  }
  .press{
     padding:3px;
     width:250px;
     font-size:25px;
     color:#0099ff;
  }
</style>
<h1 align="center" style="color: #0099ff;"><%= t("new_college") %></h1>
<body bgcolor="#f1f1f1" >
  <div class="block">
      <%= form_for :college, url: colleges_path do |f|  %>
         <br><br>
         <p>
           <%= f.text_field :name, placeholder: "College Name", class: "filling", :required => true %><br><br>
           <%= f.number_field :establish, placeholder: "Established Year", class: "filling", :required => true %><br><br>
           <%= f.submit "Add College", class: "press"%>
         </p>
      <% end %>
      <p><%= link_to "Home", "/home", {:class=>"links"} %></p>
  </div>
</body>

colleges_students_backbone/app/views/colleges/search.html.erb
<html>
  <head>
    <style>
        .block{
           background-color: orange;
           box-shadow: 0px 0px 20px;
           width:750px;
           height: 550px;
           text-align: center;
           margin-left:22%;
        }
        .links{
           color:#f1f1f1;
           font-size:40px;
           font-weight:bold;
           text-decoration: none;
        }
        table {
           border-collapse: collapse;
           text-align: center;
           margin-left:5%;
        }
        table, td, th {
           border: 2px solid #0099ff;
           padding: 4px;
        }
        .jump{
           color:#f1f1f1;
           font-weight:bold;
           text-decoration: none;
        }
        .jump:hover
        {
           font-size:120%;
        }
    </style>
    <h1 align="center" style="color: #0099ff;"><%= t("match_available") %></h1>
  </head>
  <body bgcolor="#f1f1f1">
    <div class="block">
      <% if !@college.empty? %><br><br>
        <table border="1">
          <tr>
            <th>College Name</th>
            <th>Established Year</th>
            <th>Edit Link</th>
            <th>Delete Link</th>
            <th>Students Link</th>
          </tr>
          <% @college.each do |item| %>
           <tr>
             <td><%= item.name %></td>
             <td><%= item.establish %></td>
             <td><%= link_to 'Edit College', edit_college_path(item.id), {:class=>"jump"} %></td>
             <td><%= link_to 'Delete College', college_path(item.id), method: "delete", class: "jump"%></td>
             <td><%= link_to 'College Students', college_path(item.id), {:class=>"jump"} %></td>
           </tr>
          <% end %>
        </table>
      <% else %>
          <br><br><p>No Matched College available</p>
      <% end %>
      <p>
        <%= link_to "Home", "/home" ,{:class=>"links"}%>
      </p>
    </div>
  </body>
</html>

colleges_students_backbone/app/views/colleges/show.html.erb
<style>
  .block{
    background-color: orange;
    box-shadow: 0px 0px 20px;
    width:700px;
    height: 550px;
    text-align: center;
    margin-left:22%;
  }
  .links{
    color:#f1f1f1;
    font-size:40px;
    font-weight:bold;
    text-decoration: none;
  }
  table {
    border-collapse: collapse;
    text-align: center;
    margin-left:5%;
  }
  table, td, th {
    border: 2px solid #0099ff;
    padding: 4px;
  }
  .jump{
    color:#f1f1f1;
    font-weight:bold;
    text-decoration: none;
  }
  .jump:hover
  {
    font-size:120%;
  }
</style>
<h1 align="center" style="color: #0099ff;"><%= t("college_students") %></h1>
<body bgcolor="#f1f1f1">
  <div class="block">
     <% if !@student.empty? %><br><br>
       <table border="1">
            <tr>
               <th>Student Reg.ID</th>
               <th>Department Name</th>
               <th>Year</th>
            </tr>
            <% @student.each do |item| %>
              <tr>
                <td><%= item.regid %></td>
                <td><%= item.dept %></td>
                <td><%= item.year %></td>
              </tr>
            <% end %>
      </table>
    <% else %>
      <br><br><p>No students available</p>
    <% end %>
    <p>
      <%= link_to "Home", "/home", {:class=>"links"} %>
    </p>
  </div>
</body>

colleges_students_backbone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CollegesStudentsReact</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

colleges_students_backbone/app/views/students/edit.html.erb
<style>
  .block{
       background-color: #0099ff;
       box-shadow: 0px 0px 20px;
       width:700px;
       height: 550px;
       text-align: center;
       margin-left:22%;
   }
   .links{
       color:#f1f1f1;
       font-size:40px;
       font-weight:bold;
       text-decoration: none;
   }
   .press{
       padding:3px;
       width:250px;
       font-size:25px;
       color:#0099ff;
   }
   .filling{
       padding:3px;
       width:250px;
       height:25px;
       font-size:25px;
   }
</style>
<h1 align="center" style="color: #0099ff;"><%= t("edit_student") %></h1>
<body bgcolor="#f1f1f1">
  <div class="block"><br><br>
    <%= form_for :student, url: student_path(@student), method: "put" do |f| %>
      <p>
        <%= f.collection_select(:college_id, College.all, :id, :name) %><br><br>
        <%= f.number_field :regid, placeholder: "Register ID", class: "filling", :required => true  %><br><br>
        <%= f.text_field :dept, placeholder: "Department Name", class: "filling", :required => true  %><br><br>
        <%= f.number_field :maths, placeholder: "Math Marks", class: "filling", :required => true  %><br><br>
        <%= f.number_field :physics, placeholder: "Physics Marks", class: "filling", :required => true  %><br><br>
        <%= f.number_field :chemistry, placeholder: "Chemistry Marks", class: "filling", :required => true  %><br><br>
        <%= f.number_field :year, placeholder: "Year", class: "filling", :required => true %><br><br>
        <%= f.submit "Submit", class: "press" %><br><br>
      </p>
    <% end %>
    <p>
      <%= link_to "Home", "/home", {:class=>"links"} %>
    </p>
  </div>
</body>

colleges_students_backbone/app/views/students/index.html.erb
<html>
  <head>
    <style>
      .block{
         background-color: orange;
         box-shadow: 0px 0px 20px;
         width:800px;
         height: 550px;
         text-align: center;
         margin-left:22%;
      }
      .links{
         color:#f1f1f1;
         font-size:40px;
         font-weight:bold;
         text-decoration: none;
      }
      table {
         border-collapse: collapse;
         text-align: center;
         margin-left:5%;
      }
      table, td, th {
         border: 2px solid #0099ff;
         padding: 4px;
      }
      .jump{
         color:#f1f1f1;
         font-weight:bold;
         text-decoration: none;
      }
      .jump:hover
      {
         font-size:120%;
      }
    </style>
    <h1 align="center" style="color: #0099ff;"><%= t("available_students") %></h1>
  </head>
  <body bgcolor="#f1f1f1">
    <div class="block">
      <% if !@students.blank? %><br><br>
        <table border="1">
          <tr>
            <th>Reg.ID</th>
            <th>Dept Name</th>
            <th>Maths</th>
            <th>Physics</th>
            <th>Chemistry</th>
            <th>Year</th>
            <th>College Name</th>
            <th>Edit Link</th>
            <th>Delete Link</th>
          </tr>
          <% @details.each do |stu, clg| %>
           <tr>
             <td><%= stu.regid %></td>
             <td><%= stu.dept %></td>
             <td><%= stu.maths %></td>
             <td><%= stu.physics %></td>
             <td><%= stu.chemistry %></td>
             <td><%= stu.year %></td>
             <th><%= clg %></td>
             <td><%= link_to 'Edit Student', edit_student_path(stu.id), {:class=>"jump"} %></td>
             <td><%= link_to 'Delete Student', student_path(stu.id), method: "delete", class: "jump"%></td>
           </tr>
          <% end %>
        </table>
      <% else %>
          <br><br><p>No Students available</p>
      <% end %>
      <p>
        <%= link_to "Home", "/home" ,{:class=>"links"}%>
      </p>
    </div>
  </body>
</html>

colleges_students_backbone/app/views/students/new.html.erb
<style>
  .block{
       background-color: #0099ff;
       box-shadow: 0px 0px 20px;
       width:700px;
       height: 550px;
       text-align: center;
       margin-left:22%;
  }
  .links{
       color:#f1f1f1;
       font-size:40px;
       font-weight:bold;
       text-decoration: none;
  }
  .press{
       padding:3px;
       width:250px;
       font-size:25px;
       color:#0099ff;
  }
  .filling{
       padding:3px;
       width:250px;
       height:25px;
       font-size:25px;
  }
</style>
<h1 align="center" style="color: #0099ff;"><%= t("new_student") %></h1>
<body bgcolor="#f1f1f1">
  <div class="block"><br><br>
    <%= form_for :student, url: students_path do |f| %>
      <p>
        <%= f.collection_select(:college_id, College.all, :id, :name) %><br><br>
        <%= f.number_field :regid, placeholder: "Register ID", class: "filling", :required => true  %><br><br>
        <%= f.text_field :dept, placeholder: "Department Name", class: "filling", :required => true  %><br><br>
        <%= f.number_field :maths, placeholder: "Math Marks", class: "filling", :required => true  %><br><br>
        <%= f.number_field :physics, placeholder: "Physics Marks", class: "filling", :required => true  %><br><br>
        <%= f.number_field :chemistry, placeholder: "Chemistry Marks", class: "filling", :required => true  %><br><br>
        <%= f.number_field :year, placeholder: "Year", class: "filling", :required => true %><br><br>
        <%= f.submit "Add Student", class: "press" %><br><br>
      </p>
    <% end %>
    <p>
      <%= link_to "Home", "/home", {:class=>"links"} %>
    </p>
  </div>
</body>

colleges_students_backbone/app/views/students/query.html.erb
<html>
  <head>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <script type="text/javascript">
     $(document).ready(function(){
       $(".js-example-basic-multiple").select2({
            placeholder: "Select Subjects",
            allowClear: true
       });
     });
    </script>
    <style>
        .block{
            background-color: orange;
            box-shadow: 0px 0px 20px;
            width:700px;
            text-align: center;
            margin-left:22%;
            padding: 10px;
        }
        .links{
            color:#f1f1f1;
            font-size:40px;
            font-weight:bold;
            text-decoration: none;
        }
        table {
            border-collapse: collapse;
            text-align: center;
        }
        table, td, th {
            border: 2px solid #0099ff;
            padding: 4px;
        }
        #display{
            width: 300px;
            height: 90px;
        }
        .press{
            padding:3px;
            width:150px;
            font-size:20px;
            color:#0099ff;
        }
    </style>
    <h1 align="center" style="color: #0099ff; font-size:35px;">Filterations on Student</h1>
  </head>
  <body bgcolor="#f1f1f1">
    <div class="block">
      <center><br>
        <%= react_component 'Students' %>
      <p>
        <%= link_to "Home", "/home" ,{:class=>"links"}%>
      </p>
      </center>
    </div>
  </body>
</html>