rails_assignments/ecommerce/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "orders/home"
  resources :orders
  resources :customers
  resources :items
end

rails_assignments/ecommerce/app/models/customer.rb
class Customer < ApplicationRecord

  validates :city, :name, presence: true, format: { with: /\A[a-zA-Z]+\z/ }
  validates :email, presence: true
  validates :pincode, presence: true, numericality: { only_integer: true}, format: { with: /\A[+-]?\d+\z/ }
  has_many :orders, dependent: :destroy

  scope :cutomer_on_id, -> (id)  { Customer.find(id)}

end

rails_assignments/ecommerce/app/models/item.rb
class Item < ApplicationRecord

  validates :item_name, presence: true, format: { with: /\A[a-zA-Z]+\z/ }
  validates :price, presence: true, numericality: true
  has_many :orders, dependent: :destroy

  scope :item_on_id, -> (id)  { Item.find(id)}

end

rails_assignments/ecommerce/app/models/order.rb
class Order < ApplicationRecord

  validates :customer_id, :item_id, presence: true, numericality: { only_integer: true}, format: { with: /\A[+-]?\d+\z/ }
  belongs_to :customer
  belongs_to :item

end

rails_assignments/ecommerce/app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    @customers = Customer.select('id, name, email, city, pincode').all
  end

  def new
    @customers = Customer.new
  end

  def show
  	@customer_orders = Customer.cutomer_on_id(params[:id]).orders
  end

  def create
    Customer.new(params.require(:customers).permit!).save
    redirect_to customers_path
  end

  def edit
    @customers = Customer.cutomer_on_id(params[:id])
  end

  def update
    Customer.cutomer_on_id(params[:id]).update_attributes(params.require(:customers).permit!)
    redirect_to customers_path
  end

  def destroy
    Customer.cutomer_on_id(params[:id]).destroy
    redirect_to customers_path
  end

end

rails_assignments/ecommerce/app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @items = Item.new
  end

  def create
    Item.new(params.require(:items).permit!).save
    redirect_to items_path
  end

  def edit
    @items = Item.item_on_id(params[:id])
  end

  def update
    Item.item_on_id(params[:id]).update_attributes(params.require(:items).permit!)
    redirect_to items_path
  end

  def destroy
    Item.item_on_id(params[:id]).destroy
    redirect_to items_path
  end

end

rails_assignments/ecommerce/app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def home
  end

  def index
    @orders = Order.includes(:customer, :item).pluck(:name, :item_name)
  end

  def new
    @orders = Order.new
  end

  def create
    Order.new(params.require(:orders).permit!).save
    redirect_to orders_home_path
  end

  def destroy
    orders = Order.find(params[:id])
    cust_id = orders.customer_id
    orders.destroy
    redirect_to customer_path(cust_id)
  end


end

rails_assignments/ecommerce/app/helpers/customers_helper.rb
module CustomersHelper
end

rails_assignments/ecommerce/app/helpers/items_helper.rb
module ItemsHelper
end

rails_assignments/ecommerce/app/helpers/orders_helper.rb
module OrdersHelper
end

rails_assignments/ecommerce/app/views/customers/edit.html.erb
<style>
    .block{
        background-color: orange;
        box-shadow: 0px 0px 20px;
        width:700px;
        height: 550px;
        text-align: center;
        margin-left:22%;
    }
    .filling{
        padding:3px;
        width:250px;
        height:25px;
        font-size:25px;
    }
    .press{
        padding:3px;
        width:250px;
        font-size:25px;
        color:#0099ff;
    }
</style>
<h1 align="center" style="color: #0099ff;">Editing A Customer</h1>
<body bgcolor="#f1f1f1">
  <div class="block">
    <%= form_for :customers, url: customer_path(@customers), method: "put" do |f|%>
       <br><br><p>
         <%= f.text_field :name, placeholder: "Customer Name", class: "filling", :required => true  %><br><br>
         <%= f.email_field :email, placeholder: "Customer Email", class: "filling", :required => true %><br><br>
         <%= f.text_field :city, placeholder: "Customer City", class: "filling", :required => true %><br><br>
         <%= f.number_field :pincode, placeholder: "Customer Pin-code", class: "filling", :required => true %><br><br>
         <%= f.submit "Submit Changes", class: "press" %>
       </p>
    <% end %>
  </div>
</body>

rails_assignments/ecommerce/app/views/customers/index.html.erb
<html>
  <head>
    <style>
        .block{
           background-color: orange;
           box-shadow: 0px 0px 20px;
           width:750px;
           height: 550px;
           text-align: center;
           margin-left:22%;
        }
        .links{
           color:#f1f1f1;
           font-size:40px;
           font-weight:bold;
           text-decoration: none;
        }
        table {
           border-collapse: collapse;
           text-align: center;
           margin-left:5%;
        }
        table, td, th {
           border: 2px solid #0099ff;
           padding: 4px;
        }
        .jump{
           color:#f1f1f1;
           font-weight:bold;
           text-decoration: none;
        }
        .jump:hover
        {
           font-size:120%;
        }
    </style>
    <h1 align="center" style="color: #0099ff;">All Available Customers</h1>
  </head>
  <body bgcolor="#f1f1f1">
    <div class="block">
      <% unless @customers.blank? %><br><br>
        <table border="1">
          <% @customers.each do |item| %>
           <tr>
               <td><%= item.name %></td>
               <td><%= item.email %></td>
               <td><%= item.city %></td>
               <td><%= item.pincode %></td>
               <td><%= link_to 'Edit Customer', edit_customer_path(item.id), {:class=>"jump"} %></td>
               <td><%= link_to 'Delete Customer', customer_path(item.id), method: "delete", class: "jump"%></td>
               <td><%= link_to 'Customer Orders', customer_path(item.id), {:class=>"jump"} %></td>
           </tr>
          <% end %>
        </table>
      <% else %>
          <br><br><p>No Customers available</p>
      <% end %>
      <p>
        <%= link_to "Home", orders_home_path ,{:class=>"links"}%>
      </p>
    </div>
  </body>
</html>

rails_assignments/ecommerce/app/views/customers/new.html.erb
<style>
  .block{
     background-color: orange;
     box-shadow: 0px 0px 20px;
     width:700px;
     height: 550px;
     text-align: center;
     margin-left:22%;
  }
  .links{
     color:#f1f1f1;
     font-size:40px;
     font-weight:bold;
     text-decoration: none;
  }
  .filling{
    padding:3px;
     width:250px;
     height:25px;
     font-size:25px;
  }
  .press{
     padding:3px;
     width:250px;
     font-size:25px;
     color:#0099ff;
  }
</style>
<h1 align="center" style="color: #0099ff;">Adding New Customer</h1>
<body bgcolor="#f1f1f1">
    <div class="block">
      <%= form_for :customers, url: customers_path do |f|%>
         <br><br>
         <p>
            <%= f.text_field :name, placeholder: "Customer Name", class: "filling", :required => true %><br><br>
            <%= f.email_field :email, placeholder: "Customer Email", class: "filling", :required => true %><br><br>
            <%= f.text_field :city, placeholder: "Customer City", class: "filling", :required => true %><br><br>
            <%= f.number_field :pincode, placeholder: "Customer Pin-code", class: "filling", :required => true %><br><br>
            <%= f.submit "Add Customer", class: "press"%>
         </p>
      <% end %>
    <p><%= link_to "Home", orders_home_path,{:class=>"links"} %></p>
    </div>
</body>

rails_assignments/ecommerce/app/views/customers/show.html.erb
<style>
     .block{
         background-color: orange;
         box-shadow: 0px 0px 20px;
         width:700px;
         height: 550px;
         text-align: center;
         margin-left:22%;
      }
      .links{
         color:#f1f1f1;
         font-size:40px;
         font-weight:bold;
         text-decoration: none;
      }
      table {
         border-collapse: collapse;
         text-align: center;
         margin-left:5%;
      }
      table, td, th {
         border: 2px solid #0099ff;
         padding: 4px;
      }
    .jump{
         color:#f1f1f1;
         font-weight:bold;
         text-decoration: none;
    }
    .jump:hover
    {
        font-size:120%;
    }
</style>
<h1 align="center" style="color: #0099ff;">Showing Customer Orders</h1>
<body bgcolor="#f1f1f1">
  <div class="block">
     <% unless @customer_orders.blank? %><br><br>
       <table border="1">
            <% @customer_orders.each do |order| %>
              <tr>
                <td><%= order.date %></td>
                <td><%= order.item.item_name %></td>
                <td><%= order.item.price %></td>
                <td><%= link_to "Delete Order", order_path(order.id), method: "delete", class: "jump"%></td>
              </tr>
            <% end %>
      </table>
    <% else %>
      <br><br><p>No orders available</p>
    <% end %>
    <p>
      <%= link_to "Home", orders_home_path, {:class=>"links"} %>
    </p>
  </div>
</body>

rails_assignments/ecommerce/app/views/items/edit.html.erb
<style>
    .block{
       background-color: orange;
       box-shadow: 0px 0px 20px;
       width:700px;
       height: 550px;
       text-align: center;
       margin-left:22%;
    }
    .filling{
       padding:3px;
       width:250px;
       height:25px;
       font-size:25px;
    }
    .press{
       padding:3px;
       width:250px;
       font-size:25px;
       color:#0099ff;
    }
</style>
<h1 align="center" style="color: #0099ff;">Editing An Item</h1>
<body bgcolor="#f1f1f1">
  <div class="block">
    <%= form_for :items, url: item_path(@items), method: "put" do |f|%>
      <br><br>
      <p>
         <%= f.text_field :item_name, placeholder: "Item Name", class: "filling", :required => true  %><br><br>
         <%= f.number_field :price, placeholder: "Item Price", class: "filling", :required => true, :step=>0.01 %><br><br>
         <%= f.submit "Submit Changes", class: "press"  %>
       </p>
    <% end %>
  </div>
</body>

rails_assignments/ecommerce/app/views/items/index.html.erb
<html>
  <style>
    .block{
         background-color: orange;
         box-shadow: 0px 0px 20px;
         width:700px;
         height: 550px;
         text-align: center;
         margin-left:22%;
    }
    .links{
         color:#f1f1f1;
         font-size:40px;
         font-weight:bold;
         text-decoration: none;
    }
    table {
         border-collapse: collapse;
         text-align: center;
         margin-left:5%;
    }
    table, td, th {
         border: 2px solid #0099ff;
         padding: 4px;
    }
    .jump{
         color:#f1f1f1;
         font-weight:bold;
         text-decoration: none;
    }
    .jump:hover
    {
      font-size:120%;
    }
  </style>
  <head>
    <h1 align="center" style="color: #0099ff;">All Available Items</h1>
  </head>
  <body bgcolor="#f1f1f1">
    <div class="block"><br><br>
      <% unless @items.blank? %>
        <table>
            <% @items.each do |item| %>
               <tr>
                 <td><%= item.item_name %></td>
                 <td><%= item.price %></td>
                 <td><%= link_to 'Edit Item', edit_item_path(item.id), {:class=>"jump"} %></td>
                 <td><%= link_to 'Delete Item', item_path(item.id), method: "delete" , class: "jump"%></td>
               </tr>
            <% end %>
        </table>
      <% else %>
        <p>No items available</p>
      <% end %>
      <p>
        <%= link_to "Home", orders_home_path, {:class=>"links"} %>
      </p>
    </div>
  </body>
</html>

rails_assignments/ecommerce/app/views/items/new.html.erb
<style>
  .block{
       background-color: orange;
       box-shadow: 0px 0px 20px;
       width:700px;
       height: 550px;
       text-align: center;
       margin-left:22%;
  }
  .links{
       color:#f1f1f1;
       font-size:40px;
       font-weight:bold;
       text-decoration: none;
  }
  .filling{
       padding:3px;
       width:250px;
       height:25px;
       font-size:25px;
  }
  .press{
       padding:3px;
       width:250px;
       font-size:25px;
       color:#0099ff;
  }
</style>
<h1 align="center" style="color: #0099ff;">Adding New Item</h1>
<body bgcolor="#f1f1f1">
  <div class="block"><br><br>
    <%= form_for :items, url: items_path do |f|%>
      <p>
          <%= f.text_field :item_name, placeholder: "Item Name", class: "filling", :required => true  %><br><br>
          <%= f.number_field :price, placeholder: "Item Price", class: "filling", :required => true, :step=> 0.01 %><br><br>
          <%= f.submit "Add Item" , class: "press"%>
      </p>
    <% end %>
    <p>
      <%= link_to "Home", orders_home_path,{:class=>"links"} %>
    </p>
  </div>
</body>

rails_assignments/ecommerce/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails_assignments/ecommerce/app/views/orders/home.html.erb
<html>
  <head>
    <style>
       .left_div{
         float: left;
         background-color: orange;
         width:400px;
         height:550px;
         margin-left: 2%;
         box-shadow: 0px 0px 10px black;
        text-align:center;
       }
       .mid_div{
         float: left;
         background-color: #0099ff;
         width:400px;
         height:550px;
         margin-left: 1%;
         box-shadow: 0px 0px 20px black;
        text-align:center;
       }
       .right_div{
         float: right;
         background-color: orange;
         width:400px;
         height:550px;
         margin-right:2%;
         box-shadow: 0px 0px 20px black;
         text-align:center;
       }
       .links{
         color:#f1f1f1;
         font-size:40px;
         font-weight:bold;
         text-decoration: none;
       }
    </style>
    <h1 align="center" style="color: #0099ff; font-size:40px;">Ecommerce Application</h1>
  </head>
  <body bgcolor="#f1f1f1">
    <div class="block">
      <p>
        <div class="left_div"><br><br><br><br><br><br><br>
          <%= link_to "Add Customer", new_customer_path, {:class=>"links"}%><br><br>
          <%= link_to "View all Customers", customers_path, {:class=>"links"}%>
        </div>
        <div class="mid_div" ><br><br><br><br><br><br><br>
          <%= link_to "Make Order", new_order_path, {:class=>"links"}%><br><br>
          <%= link_to "View all orders", orders_path, {:class=>"links"}%>
        </div>
        <div class="right_div"><br><br><br><br><br><br><br>
          <%= link_to "Add Item", new_item_path, {:class=>"links"} %><br><br>
          <%= link_to "View all Items", items_path, {:class=>"links"}%>
        </div>
      </p>
    </div>
  </body>
</html>

rails_assignments/ecommerce/app/views/orders/index.html.erb
<html>
  <head>
    <style>
      .block{
           background-color: #0099ff;
           box-shadow: 0px 0px 20px;
           width:700px;
           height: 550px;
           text-align: center;
           margin-left:22%;
      }
      .links{
           color:#f1f1f1;
           font-size:40px;
           font-weight:bold;
           text-decoration: none;
      }
      table {
           border-collapse: collapse;
           text-align: center;
           margin-left:5%;
      }
      table, td, th {
           border: 2px solid orange;
           padding: 4px;
      }
    </style>
    <h1 align="center" style="color: #0099ff;">All Orders Available On Website</h1>
  </head>
  <body bgcolor="#f1f1f1">
    <div class="block"><br><br>
      <% unless @orders.blank? %>
        <table border='1'>
          <% @orders.each do |customer_name, item_name| %>
            <tr>
               <td><%= customer_name %></td>
               <td><%= item_name %></td>
            </tr>
          <% end %>
        </table>
      <% else %>
        <p>No orders available</p>
      <% end %>
      <p>
        <%= link_to "Home", orders_home_path, {:class=>"links"}%>
      </p>
    </div>
  </body>
</html>

rails_assignments/ecommerce/app/views/orders/new.html.erb
<style>
  .block{
       background-color: #0099ff;
       box-shadow: 0px 0px 20px;
       width:700px;
       height: 550px;
       text-align: center;
       margin-left:22%;
  }
  .links{
       color:#f1f1f1;
       font-size:40px;
       font-weight:bold;
       text-decoration: none;
  }
  .press{
       padding:3px;
       width:250px;
       font-size:25px;
       color:#0099ff;
  }
</style>
<h1 align="center" style="color: #0099ff;">Making New Order</h1>
<body bgcolor="#f1f1f1">
  <div class="block"><br><br>
    <%= form_for :orders, url: orders_path do |f|%>
       <p>
         <%= f.collection_select(:customer_id, Customer.select('id, name').all, :id, :name) %><br><br>
         <%= f.collection_select(:item_id, Item.select('id, item_name').all, :id, :item_name) %><br><br>
          <input type=date id=orders_date name=orders[date] /><br><br>
         <%= f.submit "Make Order", class: "press" %>
       </p>
    <% end %>
    <p>
      <%= link_to "Home", orders_home_path, {:class=>"links"} %>
    </p>
  </div>
</body>